"""shop orders

Revision ID: 3ff9e460780e
Revises: 83d1243fccec
Create Date: 2026-10-03 03:33:28.540646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff9e460780e'
down_revision: Union[str, Sequence[str], None] = '83d1243fccec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # orders.status gains the Shop steps (CHECK constraints are not autogenerated).
    op.drop_constraint(op.f('ck_orders_status_valid'), 'orders', type_='check')
    op.create_check_constraint(
        op.f('ck_orders_status_valid'), 'orders', "status IN ('pending', 'confirmed', 'ready', 'completed', 'cancelled')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
    # Fails while confirmed / ready orders exist: the older schema cannot express them.
    op.drop_constraint(op.f('ck_orders_status_valid'), 'orders', type_='check')
    op.create_check_constraint(op.f('ck_orders_status_valid'), 'orders', "status IN ('pending', 'completed', 'cancelled')")
