"""product reference images

Revision ID: f5495714ea9a
Revises: 55110109a300
Create Date: 2026-10-01 02:12:21.925779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5495714ea9a'
down_revision: Union[str, Sequence[str], None] = '55110109a300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reference_images',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('thumbnail', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_product_reference_images_merchant_id_merchants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_reference_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_reference_images'))
    )
    op.create_index(op.f('ix_product_reference_images_merchant_id'), 'product_reference_images', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_product_reference_images_product_id'), 'product_reference_images', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_reference_images_product_id'), table_name='product_reference_images')
    op.drop_index(op.f('ix_product_reference_images_merchant_id'), table_name='product_reference_images')
    op.drop_table('product_reference_images')
    # ### end Alembic commands ###
