"""paytm payments

Revision ID: 83d1243fccec
Revises: f5495714ea9a
Create Date: 2026-10-03 02:04:48.687163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d1243fccec'
down_revision: Union[str, Sequence[str], None] = 'f5495714ea9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # payments.method gains 'paytm' (CHECK constraints are not autogenerated).
    op.drop_constraint(op.f('ck_payments_method_valid'), 'payments', type_='check')
    op.create_check_constraint(op.f('ck_payments_method_valid'), 'payments', "method IN ('cash', 'upi', 'card', 'paytm')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paytm_payments',
    sa.Column('cart_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('paytm_order_id', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('txn_id', sa.String(length=64), nullable=True),
    sa.Column('bank_txn_id', sa.String(length=64), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('result_code', sa.String(length=64), nullable=True),
    sa.Column('result_msg', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'paid', 'failed', 'cancelled', 'needs_review')", name=op.f('ck_paytm_payments_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_paytm_payments_amount_positive')),
    sa.CheckConstraint('discount >= 0', name=op.f('ck_paytm_payments_discount_non_negative')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_paytm_payments_cart_id_carts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_paytm_payments_merchant_id_merchants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_paytm_payments_order_id_orders')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_paytm_payments_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paytm_payments')),
    sa.UniqueConstraint('order_id', name=op.f('uq_paytm_payments_order_id')),
    sa.UniqueConstraint('paytm_order_id', name=op.f('uq_paytm_payments_paytm_order_id'))
    )
    op.create_index(op.f('ix_paytm_payments_cart_id'), 'paytm_payments', ['cart_id'], unique=False)
    op.create_index(op.f('ix_paytm_payments_merchant_id'), 'paytm_payments', ['merchant_id'], unique=False)
    op.create_index('uq_paytm_payments_cart_id_live', 'paytm_payments', ['cart_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'needs_review')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_paytm_payments_cart_id_live', table_name='paytm_payments', postgresql_where=sa.text("status IN ('pending', 'needs_review')"))
    op.drop_index(op.f('ix_paytm_payments_merchant_id'), table_name='paytm_payments')
    op.drop_index(op.f('ix_paytm_payments_cart_id'), table_name='paytm_payments')
    op.drop_table('paytm_payments')
    # ### end Alembic commands ###
    # Fails while Paytm payments exist: they cannot be expressed in the older schema.
    op.drop_constraint(op.f('ck_payments_method_valid'), 'payments', type_='check')
    op.create_check_constraint(op.f('ck_payments_method_valid'), 'payments', "method IN ('cash', 'upi', 'card')")
