"""insight actions

Revision ID: 4762f2a3cc0a
Revises: 3ff9e460780e
Create Date: 2026-10-08 18:52:29.982671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4762f2a3cc0a'
down_revision: Union[str, Sequence[str], None] = '3ff9e460780e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_actions',
    sa.Column('insight_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('snoozed', 'dismissed', 'resolved')", name=op.f('ck_insight_actions_status_valid')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_insight_actions_merchant_id_merchants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_insight_actions_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insight_actions')),
    sa.UniqueConstraint('merchant_id', 'insight_key', name=op.f('uq_insight_actions_merchant_id_insight_key'))
    )
    op.create_index(op.f('ix_insight_actions_insight_key'), 'insight_actions', ['insight_key'], unique=False)
    op.create_index(op.f('ix_insight_actions_merchant_id'), 'insight_actions', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insight_actions_merchant_id'), table_name='insight_actions')
    op.drop_index(op.f('ix_insight_actions_insight_key'), table_name='insight_actions')
    op.drop_table('insight_actions')
    # ### end Alembic commands ###
